In [1]:
import numpy as np 
import pandas as pd

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info() #object means string

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

# Working with Dates

In [7]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [8]:
# Converting to DateTime Datatype
date['date'] = pd.to_datetime(date['date'])

In [9]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

### 1. Extract Year

In [10]:
date['date_year'] = date['date'].dt.year # YYYY:MM:DD

date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

### 2. Extract Month

In [11]:
date['date_month'] = date['date'].dt.month

date.head()

        date  product_id  city_id  orders  date_year  date_month
0 2019-12-10        5628       25       3       2019          12
1 2018-08-15        3646       14     157       2018           8
2 2018-10-23        1859       25       1       2018          10
3 2019-08-17        7292       25       1       2019           8
4 2019-01-06        4344       25       3       2019           1

### 3. Extract Day

In [12]:
date['date_day'] = date['date'].dt.day

date.head()

        date  product_id  city_id  orders  date_year  date_month  date_day
0 2019-12-10        5628       25       3       2019          12        10
1 2018-08-15        3646       14     157       2018           8        15
2 2018-10-23        1859       25       1       2018          10        23
3 2019-08-17        7292       25       1       2019           8        17
4 2019-01-06        4344       25       3       2019           1         6

### 4. Extract DayOfWeek

In [13]:
date['date_dow'] = date['date'].dt.dayofweek

date.head()

,date,product_id,city_id,orders,date_year,date_month,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,10,1
1,2018-08-15,3646,14,157,2018,8,15,2
2,2018-10-23,1859,25,1,2018,10,23,1
3,2019-08-17,7292,25,1,2019,8,17,5
4,2019-01-06,4344,25,3,2019,1,6,6

In [14]:
# Day of week Name

date['date_dow_name'] = date['date'].dt.day_name()

date.drop(columns=['product_id','city_id','orders']).head()

        date  date_year  date_month  date_day  date_dow date_dow_name
0 2019-12-10       2019          12        10         1       Tuesday
1 2018-08-15       2018           8        15         2     Wednesday
2 2018-10-23       2018          10        23         1       Tuesday
3 2019-08-17       2019           8        17         5      Saturday
4 2019-01-06       2019           1         6         6        Sunday

In [15]:
# is weekend

date['date_is_weekened'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0) #isin function

date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month,date_day,date_dow,date_dow_name,date_is_weekened
0,2019-12-10,2019,12,10,1,Tuesday,0
1,2018-08-15,2018,8,15,2,Wednesday,0
2,2018-10-23,2018,10,23,1,Tuesday,0
3,2019-08-17,2019,8,17,5,Saturday,1
4,2019-01-06,2019,1,6,6,Sunday,1

### 5. Extract Week of the Year

In [16]:
date['date_week'] = date['date'].dt.isocalendar().week

date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month,date_day,date_dow,date_dow_name,date_is_weekened,date_week
0,2019-12-10,2019,12,10,1,Tuesday,0,50
1,2018-08-15,2018,8,15,2,Wednesday,0,33
2,2018-10-23,2018,10,23,1,Tuesday,0,43
3,2019-08-17,2019,8,17,5,Saturday,1,33
4,2019-01-06,2019,1,6,6,Sunday,1,1

### 6. Extract Quarter

In [17]:
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month,date_day,date_dow,date_dow_name,date_is_weekened,date_week,quarter
0,2019-12-10,2019,12,10,1,Tuesday,0,50,4
1,2018-08-15,2018,8,15,2,Wednesday,0,33,3
2,2018-10-23,2018,10,23,1,Tuesday,0,43,4
3,2019-08-17,2019,8,17,5,Saturday,1,33,3
4,2019-01-06,2019,1,6,6,Sunday,1,1,1

### 7. Extract Semester

In [18]:
# date['semester'] = ((date['date'].dt.month - 1) // 6) + 1
date['semester'] = np.where(date['quarter'].isin([1,2]), 1,2)

date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month,date_day,date_dow,date_dow_name,date_is_weekened,date_week,quarter,semester
0,2019-12-10,2019,12,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,6,6,Sunday,1,1,1,1

### 8. Extract Time Elapsed between Dates

In [19]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 6, 25, 2, 40, 7, 545364)

In [20]:
today - date['date'].head()

0   2389 days 02:40:07.545364
1   2871 days 02:40:07.545364
2   2802 days 02:40:07.545364
3   2504 days 02:40:07.545364
4   2727 days 02:40:07.545364
Name: date, dtype: timedelta64[ns]

In [21]:
(today - date['date']).dt.days.head()

0    2389
1    2871
2    2802
3    2504
4    2727
Name: date, dtype: int64

In [22]:
# Months Passed
# np.round((today - date['date']) / np.timedelta64(1, 'M'), 0)
np.round((today - date['date']).dt.days / 30.44, 0)

0      78.0
1      94.0
2      92.0
3      82.0
4      90.0
       ...
995    93.0
996    91.0
997    86.0
998    88.0
999    80.0
Name: date, Length: 1000, dtype: float64

# Working With Time

In [23]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [24]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [25]:
# Convert to datetime datatype

time['date'] = pd.to_datetime(time['date'])

In [26]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [27]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

### Extract Time Part

In [28]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

### Time Difference

In [29]:
today - time['date']

0     4575 days 01:50:07.545364
1     4439 days 03:00:07.545364
2     4925 days 02:19:07.545364
3     4227 days 02:09:07.545364
4     4624 days 03:29:07.545364
                 ...
995   5214 days 01:50:07.545364
996   4535 days 03:26:07.545364
997   5000 days 03:03:07.545364
998   5116 days 03:06:07.545364
999   4388 days 03:15:07.545364
Name: date, Length: 1000, dtype: timedelta64[ns]

In [30]:
# in seconds

(today - time['date']) / np.timedelta64(1, 's')

0      3.952866e+08
1      3.835404e+08
2      4.255283e+08
3      3.652205e+08
4      3.995261e+08
           ...
995    4.504962e+08
996    3.918364e+08
997    4.320110e+08
998    4.420336e+08
999    3.791349e+08
Name: date, Length: 1000, dtype: float64

In [32]:
# in minutes

(today - time['date']) / np.timedelta64(1, 'm')

0      6.588110e+06
1      6.392340e+06
2      7.092139e+06
3      6.087009e+06
4      6.658769e+06
           ...
995    7.508270e+06
996    6.530606e+06
997    7.200183e+06
998    7.367226e+06
999    6.318915e+06
Name: date, Length: 1000, dtype: float64

In [33]:
# in hours

(today - time['date']) / np.timedelta64(1, 'h')

0      109801.835429
1      106539.002096
2      118202.318763
3      101450.152096
4      110979.485429
           ...
995    125137.835429
996    108843.435429
997    120003.052096
998    122787.102096
999    105315.252096
Name: date, Length: 1000, dtype: float64